/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Message {
  'id' : MessageId,
  'body' : string,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'senderName' : string,
  'roomId' : RoomId,
}
export type MessageId = bigint;
export interface MessageView {
  'id' : MessageId,
  'body' : string,
  'isMine' : boolean,
  'isRead' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'senderName' : string,
  'roomId' : RoomId,
}
export interface OnlineUser {
  'displayName' : string,
  'userId' : UserId,
  'avatarInitial' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface Room {
  'id' : RoomId,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
}
export interface RoomDetail {
  'members' : Array<User>,
  'messages' : Array<MessageView>,
  'room' : Room,
  'typingUsers' : Array<OnlineUser>,
  'onlineUsers' : Array<OnlineUser>,
}
export type RoomId = bigint;
export interface RoomSummary {
  'id' : RoomId,
  'lastMessageAt' : [] | [Timestamp],
  'lastMessagePreview' : string,
  'name' : string,
  'memberCount' : bigint,
  'isMember' : boolean,
  'description' : string,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'displayName' : string,
  'joinedAt' : Timestamp,
  'avatarInitial' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string, string], Room>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  'getRoomDetail' : ActorMethod<[RoomId], [] | [RoomDetail]>,
  'heartbeat' : ActorMethod<[RoomId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[RoomId], boolean>,
  'leaveRoom' : ActorMethod<[RoomId], boolean>,
  'listMessages' : ActorMethod<[RoomId], Array<Message>>,
  'listRooms' : ActorMethod<[], Array<RoomSummary>>,
  'markRead' : ActorMethod<[RoomId, MessageId], undefined>,
  'registerUser' : ActorMethod<[string], User>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[RoomId, string], [] | [Message]>,
  'setTyping' : ActorMethod<[RoomId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];