/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Room = IDL.Record({
  'id' : RoomId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const User = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'joinedAt' : Timestamp,
  'avatarInitial' : IDL.Text,
});
export const MessageId = IDL.Nat;
export const MessageView = IDL.Record({
  'id' : MessageId,
  'body' : IDL.Text,
  'isMine' : IDL.Bool,
  'isRead' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'senderName' : IDL.Text,
  'roomId' : RoomId,
});
export const OnlineUser = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : UserId,
  'avatarInitial' : IDL.Text,
});
export const RoomDetail = IDL.Record({
  'members' : IDL.Vec(User),
  'messages' : IDL.Vec(MessageView),
  'room' : Room,
  'typingUsers' : IDL.Vec(OnlineUser),
  'onlineUsers' : IDL.Vec(OnlineUser),
});
export const Message = IDL.Record({
  'id' : MessageId,
  'body' : IDL.Text,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'senderName' : IDL.Text,
  'roomId' : RoomId,
});
export const RoomSummary = IDL.Record({
  'id' : RoomId,
  'lastMessageAt' : IDL.Opt(Timestamp),
  'lastMessagePreview' : IDL.Text,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'isMember' : IDL.Bool,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getRoomDetail' : IDL.Func([RoomId], [IDL.Opt(RoomDetail)], ['query']),
  'heartbeat' : IDL.Func([RoomId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'listMessages' : IDL.Func([RoomId], [IDL.Vec(Message)], ['query']),
  'listRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
  'markRead' : IDL.Func([RoomId, MessageId], [], []),
  'registerUser' : IDL.Func([IDL.Text], [User], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func([RoomId, IDL.Text], [IDL.Opt(Message)], []),
  'setTyping' : IDL.Func([RoomId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Room = IDL.Record({
    'id' : RoomId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const User = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'joinedAt' : Timestamp,
    'avatarInitial' : IDL.Text,
  });
  const MessageId = IDL.Nat;
  const MessageView = IDL.Record({
    'id' : MessageId,
    'body' : IDL.Text,
    'isMine' : IDL.Bool,
    'isRead' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'senderName' : IDL.Text,
    'roomId' : RoomId,
  });
  const OnlineUser = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : UserId,
    'avatarInitial' : IDL.Text,
  });
  const RoomDetail = IDL.Record({
    'members' : IDL.Vec(User),
    'messages' : IDL.Vec(MessageView),
    'room' : Room,
    'typingUsers' : IDL.Vec(OnlineUser),
    'onlineUsers' : IDL.Vec(OnlineUser),
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'body' : IDL.Text,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'senderName' : IDL.Text,
    'roomId' : RoomId,
  });
  const RoomSummary = IDL.Record({
    'id' : RoomId,
    'lastMessageAt' : IDL.Opt(Timestamp),
    'lastMessagePreview' : IDL.Text,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'isMember' : IDL.Bool,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getRoomDetail' : IDL.Func([RoomId], [IDL.Opt(RoomDetail)], ['query']),
    'heartbeat' : IDL.Func([RoomId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'listMessages' : IDL.Func([RoomId], [IDL.Vec(Message)], ['query']),
    'listRooms' : IDL.Func([], [IDL.Vec(RoomSummary)], ['query']),
    'markRead' : IDL.Func([RoomId, MessageId], [], []),
    'registerUser' : IDL.Func([IDL.Text], [User], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func([RoomId, IDL.Text], [IDL.Opt(Message)], []),
    'setTyping' : IDL.Func([RoomId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };